package fixer

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/Danceiny/wtool/pkg/utils"
)

// PortFixer handles port allocation
type PortFixer struct {
	WorktreePath string
	BaseOffset   int
	Services     []ServicePort
}

// ServicePort defines a port mapping
type ServicePort struct {
	Name   string
	Base   int
	EnvKey string
}

// NewPortFixer creates a new port fixer
func NewPortFixer(worktreePath string, baseOffset int, services []ServicePort) *PortFixer {
	if len(services) == 0 {
		services = []ServicePort{
			{Name: "api", Base: 8080, EnvKey: "API_PORT"},
			{Name: "frontend", Base: 3000, EnvKey: "FE_PORT"},
			{Name: "devserver", Base: 9090, EnvKey: "DEVSERVER_PORT"},
		}
	}
	return &PortFixer{
		WorktreePath: worktreePath,
		BaseOffset:   baseOffset,
		Services:     services,
	}
}

// Fix generates environment file with port assignments
func (f *PortFixer) Fix() error {
	wtIndex, err := utils.GetWorktreeIndex(f.WorktreePath)
	if err != nil {
		wtIndex = 0
	}

	// Check if main worktree
	wtInfo, err := utils.GetWorktreeInfo(f.WorktreePath)
	if err != nil {
		return err
	}

	offset := wtIndex + f.BaseOffset
	if wtInfo.IsMain {
		offset = f.BaseOffset
	}

	// Generate env file
	envPath := filepath.Join(f.WorktreePath, ".worktree.env")
	var sb strings.Builder

	wtName := filepath.Base(f.WorktreePath)
	
	sb.WriteString("# Auto-generated by wtool\n")
	sb.WriteString(fmt.Sprintf("# Worktree: %s (offset=%d)\n", wtName, offset))
	sb.WriteString("# Source this file: source .worktree.env\n\n")
	sb.WriteString(fmt.Sprintf("export WORKTREE_NAME=%s\n", wtName))
	sb.WriteString(fmt.Sprintf("export WORKTREE_OFFSET=%d\n", offset))

	for _, svc := range f.Services {
		port := svc.Base + offset
		sb.WriteString(fmt.Sprintf("export %s=%d\n", svc.EnvKey, port))
	}

	return os.WriteFile(envPath, []byte(sb.String()), 0644)
}
